swagger: '2.0'
info:
  title: copile-eu-api
  version: 1.0.0
host: user-api-2bo4cs8336hkz.apigateway.copile.cloud.goog
paths:
  /bybit/trades:
    get:
      operationId: getTrades
      parameters:
        - name: userId
          in: header
          required: false
          type: string
        - name: traderId
          in: header
          required: false
          type: string
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              success:
                type: boolean
              trades:
                type: array
                items:
                  type: object
              orders:
                type: array
                items:
                  type: object
              executionTime:
                type: integer
      x-google-backend:
        address: https://europe-west2-copile.cloudfunctions.net
        path_translation: APPEND_PATH_TO_ADDRESS
      consumes:
        - application/json
      produces:
        - application/json
  /bybit/balance:
    get:
      operationId: getBalance
      parameters:
        - name: traderId
          in: header
          required: false
          type: string
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              success:
                type: boolean
              balance:
                type: array
                items:
                  type: object
      x-google-backend:
        address: https://europe-west2-copile.cloudfunctions.net
        path_translation: APPEND_PATH_TO_ADDRESS
      consumes:
        - application/json
      produces:
        - application/json
  /bybit/order/{symbol}/{tradeId}:
    get:
      operationId: getTradeProfitLossDetails
      parameters:
        - name: symbol
          in: path
          required: true
          type: string
        - name: tradeId
          in: path
          required: true
          type: string
        - name: userId
          in: header
          required: false
          type: string
        - name: traderId
          in: header
          required: false
          type: string
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              take_profits:
                type: array
                items:
                  type: object
              stop_losses:
                type: array
                items:
                  type: object
      x-google-backend:
        address: https://europe-west2-copile.cloudfunctions.net
        path_translation: APPEND_PATH_TO_ADDRESS
      consumes:
        - application/json
      produces:
        - application/json
  /bybit/symbolData:
    get:
      operationId: symbolData
      parameters:
        - name: traderId
          in: header
          required: true
          type: string
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              success:
                type: boolean
              symbols:
                type: array
                items:
                  type: object
      x-google-backend:
        address: https://europe-west2-copile.cloudfunctions.net
        path_translation: APPEND_PATH_TO_ADDRESS
      consumes:
        - application/json
      produces:
        - application/json
  /bybit/supportedExchanges:
    get:
      operationId: supportedExchanges
      parameters:
        - name: traderId
          in: header
          required: true
          type: string
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              success:
                type: boolean
              symbols:
                type: array
                items:
                  type: object
      x-google-backend:
        address: https://europe-west2-copile.cloudfunctions.net
        path_translation: APPEND_PATH_TO_ADDRESS
      consumes:
        - application/json
      produces:
        - application/json
