from kucoin_futures.client import Trade
from ..firestore_functions import get_user_keys, get_trade_info, store_tp


def send_profit(account_id, trade_id, tp_document_id, tp_number, tp_value, tp_percentage):
    keys = get_user_keys(account_id, "kucoin")
    trade_info = get_trade_info(account_id, trade_id)
    symbol = trade_info["symbol"]
    side = trade_info["side"]

    # Connecting to Kucoin API
    client_trade = Trade(key=keys['api_key'], secret=keys['api_secret'], passphrase=keys['api_passphrase'],
                         is_sandbox=False, url='')
    # Fixing symbol, because of exceptions
    if symbol == "BTCUSDT":
        symbol = "XBTUSDTM"
    else:
        symbol = f"{symbol}M"

    position = client_trade.get_position_details(
        symbol=symbol,
    )
    leverage = str(position['realLeverage'])
    quantity = position['currentQty'] if position['currentQty'] > 0 else position['currentQty'] * (-1)
    side = 'sell' if position['currentQty'] > 0 else 'buy'
    tp_amount = int(float(quantity) * float(tp_percentage))

    # Placing Take-Profit Limit Order
    try:
        tp_order = client_trade.create_limit_order(
            symbol=symbol,
            size=tp_amount,
            price=str(tp_value),
            stop="up" if side == "sell" else "down",
            stopPriceType="TP",
            stopPrice=str(tp_value),
            side=side,
            lever=leverage,
            type='market',
            reduce_only=True,
        )
        order_id = tp_order['orderId']  # orderId generated by kucoin
        tp_dict = {
            "order_id": order_id,
            "trade_id": trade_id,
            "tp_document_id": tp_document_id,
            "tp_number": tp_number,
            "tp_value": tp_value,
            "tp_percentage": tp_percentage
        }
        store_tp(account_id, tp_dict)
        return f"Successfully placed Take-Profit {tp_value} Order for {account_id}"
    except Exception as error:
        print(error)
