from kucoin_futures.client import Trade
from ..firestore_functions import get_user_keys, get_trade_info, store_sl


def send_stoploss(account_id, trade_id, sl_document_id, sl_number, sl_value, sl_percentage):
    keys = get_user_keys(account_id, "kucoin")
    trade_info = get_trade_info(account_id, trade_id)
    symbol = trade_info["symbol"]
    side = trade_info["side"]

    # Connecting to Kucoin API
    client_trade = Trade(key=keys['api_key'], secret=keys['api_secret'], passphrase=keys['api_passphrase'],
                         is_sandbox=False, url='')
    # Fixing symbol, because of exceptions
    if symbol == "BTCUSDT":
        symbol = "XBTUSDTM"
    else:
        symbol = f"{symbol}M"

    position = client_trade.get_position_details(
        symbol=symbol,
    )
    leverage = str(position['realLeverage'])
    quantity = position['currentQty'] if position['currentQty'] > 0 else position['currentQty'] * (-1)
    side = 'sell' if position['currentQty'] > 0 else 'buy'
    sl_amount = int(float(quantity) * float(sl_percentage))

    # Placing Stop-loss Limit Order
    try:
        sl_order = client_trade.create_limit_order(
            symbol=symbol,
            size=sl_amount,
            side=side,
            lever=leverage,
            price=str(sl_value),
            stop="down" if side == "sell" else "up",
            stopPriceType="TP",
            stopPrice=str(sl_value),
            type='market',
            reduce_only=True,
        )
        order_id = sl_order['orderId']  # orderId generated by kucoin
        sl_dict = {
            "order_id": order_id,
            "trade_id": trade_id,
            "sl_document_id": sl_document_id,
            "sl_number": sl_number,
            "sl_value": sl_value,
            "sl_percentage": sl_percentage
        }
        store_sl(account_id, sl_dict)
        return f"Successfully placed Stoploss {sl_value} Order for {account_id}"
    except Exception as error:
        print(error)
