from .bingX.perpetual.v2.Perpetual import Perpetual
from ..firestore_functions import store_tp_exec
from .position import get_position
import time
import asyncio

async def send_profit(account_id, trade_id, tp_document_id, tp_number, tp_value, tp_percentage, tp_amount, position, trade_info, precisions, keys):
    max_retries = 3
    retry_count = 0
    while retry_count < max_retries:
        try:
            await profit_order(account_id, trade_id, tp_document_id, tp_number, tp_value, tp_percentage, tp_amount, position, trade_info, precisions, keys)
            return f"Successfully placed Take-Profit {tp_value} Order for {account_id}"
        except Exception as error:
            print(f"Error occurred: {error}")
            retry_count += 1
            time.sleep(5)
    return "Failed to place Take-Profit order after multiple retries"

async def profit_order(account_id, trade_id, tp_document_id, tp_number, tp_value, tp_percentage, tp_amount, position, trade_info, precisions, keys):
    try:    
        symbol = trade_info["symbol"]
        side = trade_info["side"]
        client = Perpetual(api_key=keys["api_key"], api_secret=keys["api_secret"])

        precisions_dict = {precision["symbol"]: precision for precision in precisions}

        quantityPrecision = precisions_dict.get(symbol, {}).get("quantityPrecision")
        pricePrecision = precisions_dict.get(symbol, {}).get("pricePrecision")

        position = await client.positions(
            symbol=symbol,
        )
        positionSide = position[0]["positionSide"]

        if tp_amount != None:
            tp_amount = tp_amount
        else:
            quantity = abs(float(position[0]['positionAmt']))
            
            tp_amount = round(float(quantity) * float(tp_percentage), quantityPrecision)
        # Placing Take-Profit Limit Order
        tp_order = await client.trade_order(
            symbol=symbol,
            type="TAKE_PROFIT_MARKET",
            side="BUY" if side == "Sell" else "BUY",
            positionSide=positionSide,
            stopPrice=round(float(tp_value), pricePrecision),
            quantity=tp_amount
        )
        order_id = tp_order["order"]['orderId']  # orderId generated by kucoin
        tp_dict = {
            "order_id": order_id,
            "trade_id": trade_id,
            "tp_document_id": tp_document_id,
            "tp_number": tp_number,
            "tp_value": tp_value,
            "tp_percentage": tp_percentage,
            "tp_amount": tp_amount
        }
        await store_tp_exec(account_id, tp_dict)
        return f"Successfully placed Take-Profit {tp_value} Order for {account_id}"
    except Exception as error:
        print(error)
