from .bingX.perpetual.v2.Perpetual import Perpetual
from ..firestore_functions import store_tp
from .position import get_position

async def send_profit(account_id, trade_id, tp_document_id, tp_number, tp_value, tp_percentage, tp_amount, trade_info, precisions, keys):
    symbol = trade_info["symbol"]
    side = trade_info["side"]

    client = Perpetual(api_key=keys["api_key"], api_secret=keys["api_secret"])

    precisions_dict = {precision["symbol"]: precision for precision in precisions}
    quantityPrecision = precisions_dict.get(symbol, {}).get("quantityPrecision")
    pricePrecision = precisions_dict.get(symbol, {}).get("pricePrecision")

    if str(tp_amount) != "0":
        tp_amount = tp_amount
    else:
        quantity = await get_position(account_id, trade_id, trade_info, keys)
        
        tp_amount = round(float(quantity) * float(tp_percentage), quantityPrecision)

    # Placing Take-Profit Limit Order
    try:
        tp_order = await client.trade_order(
            symbol=symbol,
            type="TRIGGER_MARKET",
            side="BUY" if side == "Sell" else "BUY",
            positionSide="SHORT" if side == "Sell" else "LONG",
            stopPrice=round(float(tp_value), pricePrecision),
            quantity=tp_amount
        )
        order_id = tp_order["order"]['orderId']  # orderId generated by kucoin
        tp_dict = {
            "order_id": order_id,
            "trade_id": trade_id,
            "tp_document_id": tp_document_id,
            "tp_number": tp_number,
            "tp_value": tp_value,
            "tp_percentage": tp_percentage,
            "tp_amount": tp_amount
        }
        await store_tp(account_id, tp_dict)
        return f"Successfully placed Take-Profit {tp_value} Order for {account_id}"
    except Exception as error:
        raise Exception(f"Error submitting take-profit for {account_id}: {error}")
