from error_handler import handle_error
from pybit.unified_trading import HTTP
from firestore_functions import store_trade
from margin import get_user_margin
from settings import get_market

async def send_trade(account_id, trade_id, margin, side, symbol, leverage, price, precision, keys):
    try:
        if type(margin) == str:
            margin = await get_user_margin(account_id, margin, trader_id, keys)

        # Connecting to Bybit API
        session = HTTP(
            testnet=True,
            api_key=keys["api_key"],
            api_secret=keys["api_secret"],
        )

        pricePrecision = int(precision["priceScale"])
        quantityPrecision = 0 if float(precision["lotSizeFilter"]["qtyStep"]).is_integer() else int(len(str(precision["lotSizeFilter"]["qtyStep"]).split(".")[1]))

        quantity = round((float(margin) * int(leverage) / float(price)), quantityPrecision) if price != "market" else round((float(margin) * int(leverage) / float(await get_market(symbol, keys))), quantityPrecision)

        # Creating order and placing all necessary Take profit positions
        try:
            create_order = await session.place_order(
                category="linear",
                side=side,
                symbol=symbol,
                orderType="Limit" if price != "market" else "Market",
                price=round(float(price), pricePrecision) if price != "market" else None,
                qty=quantity,
                timeInForce="GTC",
                reduceOnly=False,
                closeOnTrigger=False,
            )
            order_id = create_order['result']['orderId']  # order_id generated by bybit
            order_dict = {
                "trade_id": trade_id,
                "order_id": order_id,

                "symbol": symbol,
                "type": "LIMIT" if price != "market" else "MARKET",
                "side": side,
                "quantity": quantity,
                "entry": price,
                "leverage": leverage,
                "margin": margin,
                "exchange": "testnet"
            }
            await store_trade(account_id, order_dict)
            return quantity
        except Exception as error:
            print(format(error))
    except Exception as error:
        handle_error(error)
        print(error)