from kucoin_futures.client import Trade, Market
from ..firestore_functions import store_trade
from .margin import get_user_margin
import asyncio

async def send_trade(account_id, trade_id, plan_id, side, symbol, leverage, price, keys):
    margin = await get_user_margin(account_id, plan_id, keys)

    # Connecting to Kucoin API
    client_trade = Trade(key=keys['api_key'], secret=keys['api_secret'], passphrase=keys['api_passphrase'],
                         is_sandbox=False, url='')
    client = Market(key=keys['api_key'], secret=keys['api_secret'], passphrase=keys['api_passphrase'], is_sandbox=False, url='')

    side = 'buy' if side == 'Buy' else 'sell'

    if symbol.endswith("M"):
        pass
    elif symbol == "BTCUSDT":
        symbol = "XBTUSDTM"
    else:
        symbol = f"{symbol}M"

    # Getting round precision for future use
    multiplier = client.get_contract_detail(symbol=symbol)['multiplier']
    min_qty = 1 * float(multiplier)
    precision = int(len(str(min_qty).split(".")[1])) if min_qty != 1 else 0

    # Calculation right lot size for trade size
    quantity = int(round((float(margin) * int(leverage) / float(price)), precision)) / float(multiplier)

    # Placing Limit Order
    try:
        create_order = client_trade.create_limit_order(
            symbol=symbol,
            size=quantity,
            price=str(price),
            side=side,
            lever=str(int(leverage)),
            type='limit',
        )
        order_id = create_order['orderId']  # orderId generated by kucoin
        order_dict = {
            "trade_id": trade_id,
            "order_id": order_id,

            "symbol": symbol,
            "type": "LIMIT",
            "side": side,
            "quantity": quantity,
            "entry": price,
            "leverage": leverage,
            "margin": margin,
            "exchange": "kucoin"
        }
        await store_trade(account_id, order_dict)
        return f"**Successfully placed order! - {account_id} - {symbol}**"
    except Exception as error:
        print(error)