from binance.client import Client
from binance.exceptions import BinanceAPIException, BinanceOrderException
from binance.helpers import round_step_size
from ..firestore_functions import store_trade
from ..firestore_functions import get_user_keys
from ..firestore_functions import get_user_margin


def send_trade(account_id, trade_id, plan_id, side, symbol, leverage, price):
    keys = get_user_keys(account_id, "binance")
    client = Client(keys["api_key"], keys["api_secret"])

    margin = get_user_margin(account_id, plan_id)

    side = 'BUY' if side == 'Buy' else 'SELL'
    info = client.futures_exchange_info()
    symbols = info['symbols']
    for i in range(len(symbols)):
        if symbols[i]['symbol'] == symbol:
            price_precision = symbols[i]['pricePrecision']
            precision = symbols[i]['quantityPrecision']
            for symbol_filter in symbols[i]['filters']:
                if symbol_filter['filterType'] == 'PRICE_FILTER':
                    price = round_step_size(price, float(symbol_filter['tickSize']))
            quantity_limit = round((float(margin) * leverage) / float(price), price_precision)
            try:
                mode = client.futures_change_margin_type(
                    symbol=symbol,
                    marginType="CROSSED"
                )
            except BinanceAPIException as error:
                print(error)
            except BinanceOrderException as error:
                print(error)
            try:
                leverage_change = client.futures_change_leverage(
                    leverage=leverage,
                    symbol=symbol,
                )
                print(leverage_change)
            except BinanceAPIException as error:
                print(error)
            except BinanceOrderException as error:
                print(error)
            try:
                create_order = client.futures_create_order(
                    symbol=symbol,
                    side=side,
                    type='LIMIT',
                    timeinForce='GTC',
                    quantity=quantity_limit,
                    price=round(price, price_precision)
                )
                order_id = create_order['orderId']  # order_id generated by binance
                order_dict = {
                    "trade_id": trade_id,
                    "order_id": order_id,

                    "symbol": symbol,
                    "type": "LIMIT",
                    "side": side,
                    "quantity": quantity_limit,
                    "entry": price,
                    "leverage": leverage,
                    "margin": margin,
                    "exchange": "binance"
                }
                store_trade(account_id, order_dict)
                return f"**Successfully placed order! - User: {account_id} - {symbol} - Order ID: {order_id}**"
            except BinanceAPIException as error:
                print(error)
            except BinanceOrderException as error:
                print(error)
