from .kuclib.client import Trade
from ..firestore_functions import store_tp

async def send_profit(account_id, trade_id, tp_document_id, tp_number, tp_value, tp_percentage, tp_amount, trade_info, multiplier, keys):
    symbol = trade_info["symbol"]

    # Connecting to Kucoin API
    client_trade = Trade(key=keys['api_key'], secret=keys['api_secret'], passphrase=keys['api_passphrase'],
                         is_sandbox=False, url='')
    
    leverage = trade_info["leverage"]
    side = 'sell' if trade_info["side"] == "Buy" else "buy"

    # Placing Take-Profit Limit Order
    try:
        tp_order = await client_trade.create_limit_order(
            symbol=symbol,
            size=tp_amount,
            price=str(tp_value),
            stop="up" if side == "sell" else "down",
            stopPriceType="MP",
            stopPrice=str(tp_v alue),
            side=side,
            leverage=leverage,
            type='market',
            reduce_only=True,
        )
        order_id = tp_order['orderId']  # orderId generated by kucoin
        tp_dict = {
            "order_id": order_id,
            "trade_id": trade_id,
            "tp_document_id": tp_document_id,
            "tp_number": tp_number,
            "tp_value": tp_value,
            "tp_percentage": tp_percentage,
            "tp_amount": tp_amount
        }
        await store_tp(account_id, tp_dict)
        return f"Successfully placed Take-Profit {tp_value} Order for {account_id}"
    except Exception as error:
        print(error)
