from .kuclib.client import Trade
from ..firestore_functions import store_sl

async def send_stoploss(account_id, trade_id, sl_document_id, sl_number, sl_value, sl_percentage, sl_amount, trade_info, multiplier, keys):
    symbol = trade_info["symbol"]

    # Connecting to Kucoin API
    client_trade = Trade(key=keys['api_key'], secret=keys['api_secret'], passphrase=keys['api_passphrase'],
                         is_sandbox=False, url='')

    leverage = trade_info["leverage"]
    side = 'sell' if trade_info["side"] == "Buy" else "buy"
    
    min_qty = 1 * float(multiplier)
    precision = int(len(str(min_qty).split(".")[1])) if min_qty != 1 else 0

    if sl_amount == None:
        position = await client_trade.get_position_details(
            symbol=symbol,
        )
        quantity = position['currentQty'] if position['currentQty'] > 0 else position['currentQty'] * (-1)
        side = 'sell' if position['currentQty'] > 0 else 'buy'
        leverage = str(position['realLeverage'])
        sl_amount = round(float(quantity) * float(sl_percentage), precision)

    # Placing Stop-loss Limit Order
    try:
        sl_order = await client_trade.create_limit_order(
            symbol=symbol,
            size=sl_amount,
            side=side,
            leverage=leverage,
            price=str(sl_value),
            stop="down" if side == "sell" else "up",
            stopPriceType="MP",
            stopPrice=str(sl_value),
            type='market',
            reduce_only=True,
        )
        order_id = sl_order['orderId']  # orderId generated by kucoin
        sl_dict = {
            "order_id": order_id,
            "trade_id": trade_id,
            "sl_document_id": sl_document_id,
            "sl_number": sl_number,
            "sl_value": sl_value,
            "sl_percentage": sl_percentage,
            "sl_amount": sl_amount
        }
        await store_sl(account_id, sl_dict)
        return f"Successfully placed Stoploss {sl_value} Order for {account_id}"
    except Exception as error:
        print(error)
