from .kuclib.client import Trade
from ..firestore_functions import store_trade
from .margin import get_user_margin
from .settings import reformat_symbol, get_market

async def send_trade(account_id, trade_id, margin, side, symbol, leverage, price, multiplier, keys):
    try:
        if type(margin) == str:
            margin = await get_user_margin(account_id, margin, keys)

        # Connecting to Kucoin API
        client_trade = Trade(key=keys['api_key'], secret=keys['api_secret'], passphrase=keys['api_passphrase'],
                            is_sandbox=False, url='')

        side = 'buy' if side == 'Buy' else 'sell'

        symbol = reformat_symbol(symbol)

        min_qty = 1 * float(multiplier)
        quantityPrecision = int(len(str(min_qty).split(".")[1])) if min_qty != 1 else 0
        
        order_type = "limit" if price != "market" else "market"

        # Calculation right lot size for trade size
        quantity = int((round((float(margin) * int(leverage) / float(price)), quantityPrecision)) / float(multiplier)) if price != "market" else int((round((float(margin) * int(leverage) / float(await get_market(symbol, keys))), quantityPrecision)) / float(multiplier))

        # Placing Limit Order
        create_order = await client_trade.create_limit_order(
            symbol=symbol,
            size=quantity,
            price=str(price) if order_type != "market" else None,
            side=side,
            leverage=str(leverage),
            type=order_type,
        )
        order_id = create_order['orderId']  # orderId generated by kucoin
        order_dict = {
            "trade_id": trade_id,
            "order_id": order_id,
            "symbol": symbol,
            "type": order_type.upper(),
            "side": side,
            "quantity": quantity,
            "entry": price,
            "leverage": leverage,
            "margin": margin,
            "exchange": "kucoin"
        }
        await store_trade(account_id, order_dict)
        return order_dict
    except Exception as error:
        print(error)