from pybit import usdt_perpetual
from ..firestore_functions import get_user_keys, store_trade, get_user_margin


def send_trade(account_id, trade_id, plan_id, side, symbol, leverage, price):
    keys = get_user_keys(account_id, "bybit")
    margin = get_user_margin(account_id, plan_id)

    side = "Buy" if side == "BUY" else "Sell"
    # Connecting to Bybit API
    session = usdt_perpetual.HTTP(
        endpoint='https://api.bybit.com',
        api_key=keys["api_key"],
        api_secret=keys["api_secret"],
    )
    min_qty = session.query_symbol()['result']
    for item in min_qty:
        if item['name'] == symbol:
            p = len(str(item['lot_size_filter']['min_trading_qty']).split(".")[1])
            precision = int(p)
    quantity = round((float(margin) * int(leverage) / float(price)), precision)
    # Changing leverage or Margin mode to Isolated/Cross
    try:
        leverage = session.set_leverage(
            symbol=symbol,
            buy_leverage=int(leverage),
            sell_leverage=int(leverage)
        )
    except Exception as error:
        print(f"Leverage set - {account_id}")
    try:
        mode = session.cross_isolated_margin_switch(
            symbol=symbol,
            is_isolated=False,
        )
    except Exception as error:
        print(f"Switched to Cross-Margin - {account_id}")

    # Creating order and placing all necessary Take profit positions
    try:
        create_order = session.place_active_order(
            side=side,
            symbol=symbol,
            order_type="Limit",
            price=price,
            qty=quantity,
            time_in_force="GoodTillCancel",
            reduce_only=False,
            close_on_trigger=False,
        )
        order_id = create_order['result']['orderId']  # order_id generated by bybit
        order_dict = {
            "trade_id": trade_id,
            "order_id": order_id,

            "symbol": symbol,
            "type": "LIMIT",
            "side": side,
            "quantity": quantity,
            "entry": price,
            "leverage": leverage,
            "margin": margin,
            "exchange": "bybit"
        }
        store_trade(account_id, order_dict)
        return f"**Successfully placed order! - {account_id} - {order_id}**"
    except Exception as error:
        print(format(error))
