from kucoin_futures.client import Trade
from ..firestore_functions import store_sl_exec
from .precision import get_precision
import asyncio

async def send_stoploss(account_id, trade_id, sl_document_id, sl_number, sl_value, sl_percentage, sl_amount, trade_info, keys):
    symbol = trade_info["symbol"]
    side = trade_info["side"]
    precision = await get_precision(account_id, symbol, keys)

    # Connecting to Kucoin API
    client_trade = Trade(key=keys['api_key'], secret=keys['api_secret'], passphrase=keys['api_passphrase'],
                         is_sandbox=False, url='')

    position = client_trade.get_position_details(
        symbol=symbol,
    )
    leverage = str(position['realLeverage'])
    quantity = position['currentQty'] if position['currentQty'] > 0 else position['currentQty'] * (-1)
    side = 'sell' if position['currentQty'] > 0 else 'buy'
    
    if sl_amount == None:
        sl_amount = round(float(quantity) * float(sl_percentage), precision)

    # Placing Stop-loss Limit Order
    try:
        sl_order = client_trade.create_limit_order(
            symbol=symbol,
            size=sl_amount,
            side=side,
            lever=leverage,
            price=str(sl_value),
            stop="down" if side == "sell" else "up",
            stopPriceType="MP",
            stopPrice=str(sl_value),
            type='market',
            reduce_only=True,
        )
        order_id = sl_order['orderId']  # orderId generated by kucoin
        sl_dict = {
            "order_id": order_id,
            "trade_id": trade_id,
            "sl_document_id": sl_document_id,
            "sl_number": sl_number,
            "sl_value": sl_value,
            "sl_percentage": sl_percentage,
            "sl_amount": sl_amount
        }
        await store_sl_exec(account_id, sl_dict)
        return f"Successfully placed Stoploss {sl_value} Order for {account_id}"
    except Exception as error:
        print(error)
