from pybit.unified_trading import HTTP
from ..firestore_functions import store_trade
import asyncio

async def send_trade(account_id, trade_id, margin, side, symbol, leverage, price, keys):

    # Connecting to Bybit API
    session = HTTP(
        testnet=False,
        api_key=keys["api_key"],
        api_secret=keys["api_secret"],
    )

    coin_info = session.get_instruments_info(category="linear", symbol=symbol)['result']['list'][0]
    min_qty = coin_info["lotSizeFilter"]['minOrderQty']
    price_precision = int(coin_info["priceScale"])
    quantity_precision = 0 if float(coin_info["lotSizeFilter"]["qtyStep"]).is_integer() else int(len(str(coin_info["lotSizeFilter"]["qtyStep"]).split(".")[1]))
    
    quantity = round((float(margin) * int(leverage) / float(price)), quantity_precision)
    # Changing leverage or Margin mode to Isolated/Cross
    try:
        leverage_change = session.set_leverage(
            category="linear",
            symbol=symbol,
            buyLeverage=int(leverage),
            sellLeverage=int(leverage)
        )
    except Exception as error:
        pass
    try:
        margin_mode = session.set_margin_mode(
            setMarginMode="ISOLATED_MARGIN"
        )
        position_mode = session.switch_position_mode(
            category="linear",
            mode=0
        )
    except Exception as error:
        pass

    # Creating order and placing all necessary Take profit positions
    try:
        create_order = session.place_order(
            category="linear",
            side=side,
            symbol=symbol,
            orderType="Limit",
            price=price,
            qty=quantity,
            timeInForce="GTC",
            reduceOnly=False,
            closeOnTrigger=False,
        )
        order_id = create_order['result']['orderId']  # order_id generated by bybit
        order_dict = {
            "trade_id": trade_id,
            "order_id": order_id,

            "symbol": symbol,
            "type": "LIMIT",
            "side": side,
            "quantity": quantity,
            "entry": price,
            "leverage": leverage,
            "margin": margin,
            "exchange": "bybit"
        }
        await store_trade(account_id, order_dict)
        return f"**Successfully placed order! - {account_id} - {order_id}**"
    except Exception as error:
        print(format(error))